/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/models/abandoned_house/scene.gltf -o ./src/components/HouseAbandoned.jsx --shadows -T -r ./public 
Files: ./public/models/abandoned_house/scene.gltf [1.43MB] > scene-transformed.glb [850.06KB] (40%)
Author: Sengchor (https://sketchfab.com/Sengchor)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/abandoned-house-a0c01ce35a474545b805c0739806aace
Title: Abandoned House
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function HouseAbandoned(props) {
  const { nodes, materials } = useGLTF("/models/abandoned_house.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube131_Material001_0.geometry}
        material={materials["Material.001"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/models/abandoned_house.glb");
