/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/stone/scene.gltf -o src/components/Stone.jsx -r public -T 
Files: public/models/stone/scene.gltf [11.13KB] > scene-transformed.glb [1.63MB] (-14535%)
Author: Austin Beaulier (https://sketchfab.com/Austin.Beaulier)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hieroglyph-stone-pyramid-7a770008f6734b43bae9305100b73894
Title: Hieroglyph Stone Pyramid
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Stone(props) {
  const { nodes, materials } = useGLTF("/../scene-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.material_0}
        position={[5.398, -9.13, 14.529]}
        rotation={[-Math.PI, -Math.PI / 2, 0]}
      />
    </group>
  );
}

useGLTF.preload("/../scene-transformed.glb");
